import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  AlignJustify,
  ArrowDown,
  MessageCircleQuestionMark,
} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="py-8 px-6 border-b border-gray-200 flex items-center justify-between max-w-7xl mx-auto">
          <AlignJustify />
          <div>Logo Company</div>
          <MessageCircleQuestionMark />
        </nav>
        {children}
      </body>
    </html>
  );
}
